module.exports = {

    host_rpc_ip: 'localhost',
    host_rpc_port: '8545',
    // host_rpc_port: '7545',
      //contract abi and address set here
      SCHAINABI:
      '[{"constant":true,"inputs":[{"name":"_shipmentID","type":"string"}],"name":"getShipmentByID","outputs":[{"name":"_sellerID","type":"string"},{"name":"_buyerID","type":"string"},{"name":"_shipperID","type":"string"},{"name":"_shipmentStatus","type":"uint256"},{"name":"_temperatureStatus","type":"uint256"},{"name":"_temperatureBreached","type":"bool"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_shipmentID","type":"string"},{"name":"_sellerID","type":"string"},{"name":"_buyerID","type":"string"},{"name":"_shipperID","type":"string"},{"name":"_shipmentStatus","type":"uint256"},{"name":"_temperatureStatus","type":"uint256"}],"name":"createShipment","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_shipmentID","type":"string"},{"name":"_shipmentStatus","type":"uint256"}],"name":"updateShipment","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_shipmentID","type":"string"},{"name":"_temperatureStatus","type":"uint256"}],"name":"updateTemperatureStatus","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"anonymous":false,"inputs":[{"indexed":true,"name":"shipmentID","type":"string"},{"indexed":false,"name":"sellerID","type":"string"},{"indexed":false,"name":"buyerID","type":"string"},{"indexed":false,"name":"shipperID","type":"string"},{"indexed":false,"name":"shipmentStatus","type":"uint256"},{"indexed":false,"name":"temperatureStatus","type":"uint256"}],"name":"createShipmentevent","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"shipmentID","type":"string"},{"indexed":false,"name":"sellerID","type":"string"},{"indexed":false,"name":"buyerID","type":"string"},{"indexed":false,"name":"shipperID","type":"string"},{"indexed":false,"name":"shipmentStatus","type":"uint256"},{"indexed":false,"name":"temperatureStatus","type":"uint256"}],"name":"shipmentUpdateEvent","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"shipmentID","type":"string"},{"indexed":false,"name":"breachedTxt","type":"string"}],"name":"temperatureBreachedEvent","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"shipmentID","type":"string"},{"indexed":false,"name":"sellerID","type":"string"},{"indexed":false,"name":"buyerID","type":"string"},{"indexed":false,"name":"shipperID","type":"string"},{"indexed":false,"name":"shipmentStatus","type":"uint256"},{"indexed":false,"name":"temperatureStatus","type":"uint256"},{"indexed":false,"name":"temperatureBreached","type":"bool"}],"name":"getShipmentEvent","type":"event"}]',
      SCAddress: "0x189437eb61afeca1f0180b2c8d87ffd3cf53c2c2",

      TemperatureArray: [12,26,12,11,27,9,10,21,3]
};
